version: '3.7'

services:
  server:
    build: ./server/
    network_mode: "host"

  client:
    build: ./client/
    network_mode: "host"
    depends_on: 
      - server
    volumes:
      - '/tmp/.X11-unix:/tmp/.X11-unix'
    environment:
      - DISPLAY=$DISPLAY
